---
  - name: install sudo
    become: yes
    apt: name=sudo state=latest

  - name: create remote access user
    become: yes
    user:
      name: "{{ remote_access_user }}"
      groups: sudo
      append: yes
      shell: "/bin/bash"

  - name: set user password (will NOT work for changing password)
    become: yes
    user:
      name: "{{ remote_access_user }}"
      password: "{{ remote_access_user_password | password_hash('sha512') }}"
    when: remote_access_user_password is defined

  - name: set authorized keys
    include_tasks: authorized_keys.yml
    vars:
      - keys_prefix: "{{ remote_access_authorized_keys_prefix }}"
      - authorized_users: "{{ remote_access_authorized_users }}"
      - user: "{{ remote_access_user }}"

  - name: sshd configuration - clear old configuration lines
    become: yes
    lineinfile: dest="{{ remote_access_ssh_daemon_config }}" regexp="^{{ item.key }} (?!{{ item.value }})" state="absent"
    notify:
      - restart ssh daemon
    with_items: "{{remote_access_sshd_configuration}}"

  - name: sshd configuration
    become: yes
    lineinfile: dest="{{ remote_access_ssh_daemon_config }}" regexp="^.*{{ item.key }}" line="{{ item.key }} {{ item.value }}"
    notify:
      - restart ssh daemon
    with_items: "{{remote_access_sshd_configuration}}"
