---

  - name: place public ssh keys
    authorized_key: user="{{ remote_access_user }}" key="{{ lookup('file', '{{ remote_access_authorized_keys_prefix }}/{{ item }}.pub') }}"
    with_items: "{{ remote_access_authorized_users }}"

  - name: disable ssh password login
    become: yes
    lineinfile: dest={{ remote_access_ssh_daemon_config }} line="PasswordAuthentication no"
    notify:
      - restart ssh daemon
