---
  - name: install sudo
    become: yes
    apt: name=sudo state=latest

  - name: create remote access user
    become: yes
    user:
      name: "{{ remote_access_user }}"
      password: "{{ remote_access_user_password | password_hash('sha512') }}"
      groups: sudo
      append: yes
      shell: "/bin/bash"
    when: remote_access_user_password is defined

  - name: collect public keys of authorized users
    set_fact:
      remote_access_authorized_keys: "{{remote_access_authorized_keys}}{{ lookup('file', '{{ remote_access_authorized_keys_prefix }}/{{ item }}.pub') }}\n"
    with_items: "{{ remote_access_authorized_users }}"

  - name: place public ssh keys
    become: yes
    authorized_key: 
      user: "{{ remote_access_user }}"
      key: "{{ remote_access_authorized_keys }}"
      exclusive: yes

  - name: sshd configuration - clear old configuration lines
    become: yes
    lineinfile: dest="{{ remote_access_ssh_daemon_config }}" regexp="^{{ item.key }} (?!{{ item.value }})" state="absent"
    notify:
      - restart ssh daemon
    with_items: "{{remote_access_sshd_configuration}}"

  - name: sshd configuration
    become: yes
    lineinfile: dest="{{ remote_access_ssh_daemon_config }}" regexp="^.*{{ item.key }}" line="{{ item.key }} {{ item.value }}"
    notify:
      - restart ssh daemon
    with_items: "{{remote_access_sshd_configuration}}"
